### ISSUE TITLE
Shapes are not perfect

### ISSUE THREAD

**Issue by Souvik34** [dhruvpatidar359/nextdraw#19]
**Describe the bug**
When I click the rectangle button there is no perfect rectangle formed

**To Reproduce**
1. Go to 'Nav bar'
2. Click on 'Rectangle button'
3. Draw the rectangle

**Expected behavior**
A perfect shape would be drawn with single line

**Screenshots**
<img width="960" alt="image" src="https://github.com/dhruvpatidar359/nextdraw/assets/98397984/ef929159-c9a2-4c11-893f-5c6284c06729">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 11
 - Browser [e.g. chrome, safari]- Chrome

**Smartphone (please complete the following information):**

**Additional context**
Please assign the task to me

**Comment by dhruvpatidar359** [comment]
Hi @Souvik34 , thanks for opening an issue . I think you have selected the slopiness option 3rd . That's why the rectangles are of that shape that you are seeing . May you please check one time .

**Comment by dhruvpatidar359** [comment]
> Hi @Souvik34 , thanks for opening the issue . I think you have selected the slopiness option 3rd . That's why the rectangles are of that shape that you are seeing . May you please check one time .

**Comment by Souvik34** [comment]
No there are multiple lines if I create any shape. 
<img width="960" alt="image" src="https://github.com/dhruvpatidar359/nextdraw/assets/98397984/7e347497-a50f-48b1-a749-a66345e31193">

**Comment by dhruvpatidar359** [comment]
@Souvik34  yes , these multiple lines are due to the sloppiness . We can change the sloppiness to a value so that this multiple lines will disappear . For such case you have to look into the rough.js docs and find how the sloppiness is handled. 

What we can do in this case , is add a slide bar or some thing like fuzzy value selector for the sloppiness . You may work on creating the same for the issue that you are pointing out . In that case person may select the settings that he want. 

You may start working on this.
